-- MySQL Script generated by MySQL Workbench
-- Tue Apr 12 13:12:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbBiblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbBiblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbBiblioteca` DEFAULT CHARACTER SET utf8 ;
USE `dbBiblioteca` ;

-- -----------------------------------------------------
-- Table `dbBiblioteca`.`tbLivro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBiblioteca`.`tbLivro` (
  `idtbLivro` INT NOT NULL,
  `tbLivro_Titulo` VARCHAR(45) NULL,
  `tbLivroAutor` VARCHAR(45) NULL,
  `tbLivro_Preço` VARCHAR(45) NULL,
  PRIMARY KEY (`idtbLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbBiblioteca`.`tbLeitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBiblioteca`.`tbLeitor` (
  `idtbLeitor` INT NOT NULL,
  `tbLeitor_Nome` VARCHAR(45) NULL,
  `tbLeitor_Cpost` VARCHAR(45) NULL,
  `tbLeitor_cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idtbLeitor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbBiblioteca`.`tbRequesicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBiblioteca`.`tbRequesicao` (
  `idtbRequesicao` INT NOT NULL,
  `tbDataR` VARCHAR(45) NULL,
  `tbDataE` VARCHAR(45) NULL,
  `tbLeitor_idtbLeitor` INT NOT NULL,
  `tbLivro_idtbLivro` INT NOT NULL,
  PRIMARY KEY (`idtbRequesicao`, `tbLeitor_idtbLeitor`, `tbLivro_idtbLivro`),
  INDEX `fk_tbRequesicao_tbLeitor_idx` (`tbLeitor_idtbLeitor` ASC) VISIBLE,
  INDEX `fk_tbRequesicao_tbLivro1_idx` (`tbLivro_idtbLivro` ASC) VISIBLE,
  CONSTRAINT `fk_tbRequesicao_tbLeitor`
    FOREIGN KEY (`tbLeitor_idtbLeitor`)
    REFERENCES `dbBiblioteca`.`tbLeitor` (`idtbLeitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbRequesicao_tbLivro1`
    FOREIGN KEY (`tbLivro_idtbLivro`)
    REFERENCES `dbBiblioteca`.`tbLivro` (`idtbLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tblivro (idtbLivro, tbLivro_Titulo, tbLivroAutor, tbLivro_Preço)
VALUES ('100', 'Os Maias', 'Eça de Queiroz','110€');
