-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 10:54:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema skatersdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema skatersdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skatersdb` DEFAULT CHARACTER SET utf8 ;
USE `skatersdb` ;

-- -----------------------------------------------------
-- Table `skatersdb`.`Skaters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Skaters` (
  `idSkaters` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `idade` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `anos_de_skate` INT NULL,
  `nacionalidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idSkaters`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Marcas` (
  `idMarcas` INT NOT NULL,
  `nome_marca` VARCHAR(45) NULL,
  `ganhos_anuais` VARCHAR(45) NULL,
  PRIMARY KEY (`idMarcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Competicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Competicoes` (
  `idCompeticoes` INT NOT NULL,
  `data` DATE NULL,
  `ganhador` VARCHAR(45) NULL,
  `patrocinadores` VARCHAR(45) NULL,
  `nome_competicao` VARCHAR(45) NULL,
  `Marcas_idMarcas` INT NOT NULL,
  PRIMARY KEY (`idCompeticoes`, `Marcas_idMarcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Rodas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Rodas` (
  `idRodas` INT NOT NULL,
  `perfil` VARCHAR(45) NULL,
  `preco_roda` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  PRIMARY KEY (`idRodas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Shapes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Shapes` (
  `idshape` INT NOT NULL,
  `material` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  PRIMARY KEY (`idshape`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Lixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Lixas` (
  `idLixas` INT NOT NULL,
  `tamanho` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  PRIMARY KEY (`idLixas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Trucks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Trucks` (
  `idTrucks` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `peso` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  PRIMARY KEY (`idTrucks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`rolamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`rolamentos` (
  `idrolamentos` INT NOT NULL,
  `abec` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  PRIMARY KEY (`idrolamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Sapatilhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Sapatilhas` (
  `idSapatilhas` INT NOT NULL,
  `local_producao` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  `material` VARCHAR(45) NULL,
  PRIMARY KEY (`idSapatilhas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Competicoes_has_Skaters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Competicoes_has_Skaters` (
  `Competicoes_idCompeticoes` INT NOT NULL,
  `Competicoes_Marcas_idMarcas` INT NOT NULL,
  `Skaters_idSkaters` INT NOT NULL,
  PRIMARY KEY (`Competicoes_idCompeticoes`, `Competicoes_Marcas_idMarcas`, `Skaters_idSkaters`),
  INDEX `fk_Competicoes_has_Skaters_Skaters1_idx` (`Skaters_idSkaters` ASC) VISIBLE,
  INDEX `fk_Competicoes_has_Skaters_Competicoes1_idx` (`Competicoes_idCompeticoes` ASC, `Competicoes_Marcas_idMarcas` ASC) VISIBLE,
  CONSTRAINT `fk_Competicoes_has_Skaters_Competicoes1`
    FOREIGN KEY (`Competicoes_idCompeticoes` , `Competicoes_Marcas_idMarcas`)
    REFERENCES `skatersdb`.`Competicoes` (`idCompeticoes` , `Marcas_idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Competicoes_has_Skaters_Skaters1`
    FOREIGN KEY (`Skaters_idSkaters`)
    REFERENCES `skatersdb`.`Skaters` (`idSkaters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Marcas_has_Skaters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Marcas_has_Skaters` (
  `Marcas_idMarcas` INT NOT NULL,
  `Skaters_idSkaters` INT NOT NULL,
  PRIMARY KEY (`Marcas_idMarcas`, `Skaters_idSkaters`),
  INDEX `fk_Marcas_has_Skaters_Skaters1_idx` (`Skaters_idSkaters` ASC) VISIBLE,
  INDEX `fk_Marcas_has_Skaters_Marcas1_idx` (`Marcas_idMarcas` ASC) VISIBLE,
  CONSTRAINT `fk_Marcas_has_Skaters_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `skatersdb`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Marcas_has_Skaters_Skaters1`
    FOREIGN KEY (`Skaters_idSkaters`)
    REFERENCES `skatersdb`.`Skaters` (`idSkaters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Marcas_has_Shapes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Marcas_has_Shapes` (
  `Marcas_idMarcas` INT NOT NULL,
  `Shapes_idshape` INT NOT NULL,
  PRIMARY KEY (`Marcas_idMarcas`, `Shapes_idshape`),
  INDEX `fk_Marcas_has_Shapes_Shapes1_idx` (`Shapes_idshape` ASC) VISIBLE,
  INDEX `fk_Marcas_has_Shapes_Marcas1_idx` (`Marcas_idMarcas` ASC) VISIBLE,
  CONSTRAINT `fk_Marcas_has_Shapes_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `skatersdb`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Marcas_has_Shapes_Shapes1`
    FOREIGN KEY (`Shapes_idshape`)
    REFERENCES `skatersdb`.`Shapes` (`idshape`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Trucks_has_Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Trucks_has_Marcas` (
  `Trucks_idTrucks` INT NOT NULL,
  `Marcas_idMarcas` INT NOT NULL,
  PRIMARY KEY (`Trucks_idTrucks`, `Marcas_idMarcas`),
  INDEX `fk_Trucks_has_Marcas_Marcas1_idx` (`Marcas_idMarcas` ASC) VISIBLE,
  INDEX `fk_Trucks_has_Marcas_Trucks1_idx` (`Trucks_idTrucks` ASC) VISIBLE,
  CONSTRAINT `fk_Trucks_has_Marcas_Trucks1`
    FOREIGN KEY (`Trucks_idTrucks`)
    REFERENCES `skatersdb`.`Trucks` (`idTrucks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trucks_has_Marcas_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `skatersdb`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`rolamentos_has_Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`rolamentos_has_Marcas` (
  `rolamentos_idrolamentos` INT NOT NULL,
  `Marcas_idMarcas` INT NOT NULL,
  PRIMARY KEY (`rolamentos_idrolamentos`, `Marcas_idMarcas`),
  INDEX `fk_rolamentos_has_Marcas_Marcas1_idx` (`Marcas_idMarcas` ASC) VISIBLE,
  INDEX `fk_rolamentos_has_Marcas_rolamentos1_idx` (`rolamentos_idrolamentos` ASC) VISIBLE,
  CONSTRAINT `fk_rolamentos_has_Marcas_rolamentos1`
    FOREIGN KEY (`rolamentos_idrolamentos`)
    REFERENCES `skatersdb`.`rolamentos` (`idrolamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rolamentos_has_Marcas_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `skatersdb`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Lixas_has_Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Lixas_has_Marcas` (
  `Lixas_idLixas` INT NOT NULL,
  `Marcas_idMarcas` INT NOT NULL,
  PRIMARY KEY (`Lixas_idLixas`, `Marcas_idMarcas`),
  INDEX `fk_Lixas_has_Marcas_Marcas1_idx` (`Marcas_idMarcas` ASC) VISIBLE,
  INDEX `fk_Lixas_has_Marcas_Lixas1_idx` (`Lixas_idLixas` ASC) VISIBLE,
  CONSTRAINT `fk_Lixas_has_Marcas_Lixas1`
    FOREIGN KEY (`Lixas_idLixas`)
    REFERENCES `skatersdb`.`Lixas` (`idLixas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lixas_has_Marcas_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `skatersdb`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Rodas_has_Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Rodas_has_Marcas` (
  `Rodas_idRodas` INT NOT NULL,
  `Marcas_idMarcas` INT NOT NULL,
  PRIMARY KEY (`Rodas_idRodas`, `Marcas_idMarcas`),
  INDEX `fk_Rodas_has_Marcas_Marcas1_idx` (`Marcas_idMarcas` ASC) VISIBLE,
  INDEX `fk_Rodas_has_Marcas_Rodas1_idx` (`Rodas_idRodas` ASC) VISIBLE,
  CONSTRAINT `fk_Rodas_has_Marcas_Rodas1`
    FOREIGN KEY (`Rodas_idRodas`)
    REFERENCES `skatersdb`.`Rodas` (`idRodas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rodas_has_Marcas_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `skatersdb`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skatersdb`.`Sapatilhas_has_Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skatersdb`.`Sapatilhas_has_Marcas` (
  `Sapatilhas_idSapatilhas` INT NOT NULL,
  `Marcas_idMarcas` INT NOT NULL,
  PRIMARY KEY (`Sapatilhas_idSapatilhas`, `Marcas_idMarcas`),
  INDEX `fk_Sapatilhas_has_Marcas_Marcas1_idx` (`Marcas_idMarcas` ASC) VISIBLE,
  INDEX `fk_Sapatilhas_has_Marcas_Sapatilhas1_idx` (`Sapatilhas_idSapatilhas` ASC) VISIBLE,
  CONSTRAINT `fk_Sapatilhas_has_Marcas_Sapatilhas1`
    FOREIGN KEY (`Sapatilhas_idSapatilhas`)
    REFERENCES `skatersdb`.`Sapatilhas` (`idSapatilhas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sapatilhas_has_Marcas_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `skatersdb`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
